accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

bloguinho/urls.py
from django.urls import path
from bloguinho import views

urlpatterns = [
    path('', views.HomeListView.as_view(), name='home'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new', views.PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete')
]

reservas/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'), # /reservas/
    url(r'^(?P<cliente_id>[0-9]+)/$', views.detalhe, name='detalhe'), # /reservas/1/
    url(r'^(?P<cliente_id>[0-9]+)/lista/$', views.reservas, name='reservas'), # /reservas/1/lista
    url(r'^(?P<cliente_id>[0-9]+)/confirma/$', views.confirma, name='confirma'), # /reservas/1/confirma
]

umas_e_ostras/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservas/', include(('reservas.urls', 'reservas'), namespace='reservas')),
    path('bloguinho/', include('bloguinho.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

bloguinho/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.body
    
    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

reservas/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Cliente(models.Model):
    nome = models.CharField(max_length=200)
    endereco = models.CharField(max_length=200)
    telefone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    registrado_em = models.DateTimeField('data do registro')

    def reservas_nao_confirmadas(self):
        return self.reserva_set.filter(confirmada=False)
    
    def reservas_confirmadas(self):
        return self.reserva_set.filter(confirmada=True)

    def __str__(self):
        return self.nome
    
    def registro_eh_antigo(self):
        um_ano = timezone.now() - timezone.timedelta(days = 365)
        return self.registrado_em < um_ano

    registro_eh_antigo.admin_order_field = 'registrado_em' # indica o nome do campo a ser usado na ordenação
    registro_eh_antigo.boolean = True # indica que a coluna é boolean pra mostrar o icone inves de True ou False
    registro_eh_antigo.short_description = 'Cliente é antigo?' # Muda o nome da coluna pra mostrar


class Reserva(models.Model):
    data_reserva = models.DateTimeField('data da reserva')
    data_evento = models.DateTimeField('data do evento')
    pessoas = models.IntegerField(default=0)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    confirmada = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.cliente} - {self.data_evento}"

bloguinho/forms.py
from django.forms import ModelForm

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

bloguinho/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from bloguinho.models import Post
from django.urls import reverse_lazy

# Create your views here.

class HomeListView(ListView):
    model = Post
    template_name = 'bloguinho/home.html'

class PostDetailView(DetailView):
    model = Post
    template_name = 'bloguinho/detail.html'

class PostCreateView(CreateView):
    model = Post
    template_name = 'bloguinho/new_post.html'
    fields = '__all__'

class PostUpdateView(UpdateView):
    model = Post
    fields = ['body']
    template_name = 'bloguinho/post_edit.html'

class PostDeleteView(DeleteView):
    model = Post
    template_name = 'bloguinho/post_delete.html'
    success_url = reverse_lazy('home') # não executa a url até terminar de deletar o post

reservas/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView

from .models import Cliente

def index(request):
    ordem = request.GET.get('ordem', 'registrado_em')
    direcao = request.GET.get('direcao', 'desc')
    campos = (field.name for field in Cliente._meta.fields)

    if ordem not in campos:
        ordem = 'registrado_em'

    if direcao == 'desc':
        direcao = '-'
    else:
        direcao = ''
    ordenacao = f'{direcao}{ordem}' #-nome ou nome

    ultimos_clientes = Cliente.objects.order_by(ordenacao)
    return render(request, 'reservas/index.html', {'ultimos_clientes': ultimos_clientes})

"""
class IndexView(ListView):
    model = Cliente
    template_name='reservas/index.html'
"""
def detalhe(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    # Para listas é get_list_or_404
    return render(request, 'reservas/detalhe.html', {'cliente': cliente})

def reservas(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    return render(request, 'reservas/reservas.html', {'cliente': cliente})

def confirma(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    confirmados = request.POST.getlist('confirmacao')
    for reserva_id in confirmados: # pega os values dos inputs,que possuem os ids das reservas
        try:
            reserva = cliente.reserva_set.get(pk=reserva_id)
        except(KeyError, Reserva.DoesNotExist):
            # Reapresenta o form do cliente 
            return render('reservas/detalhe.html', {'cliente': cliente, 'error_message':"Código de reserva não encontrado.",})
        else:
            reserva.confirmada = True
            reserva.save()
            return HttpResponseRedirect(reverse('reservas:reservas', args=(cliente.id,)))

reservas/templates/detalhe.html
{% extends "base.html" %} {% block conteudo %}
<h1>{{cliente.nome}}</h1>
{% if error_message %}
<p>
    <strong>{{error_message}}</strong>
</p>
{% endif %}

<form action="{% url 'reservas:confirma' cliente.id %}" method="post">
    {% csrf_token %} {% for reserva in cliente.reservas_nao_confirmadas %}
    <input type="checkbox" name="confirmacao" id="confirmacao{{forloop.counter}}" value="{{reserva.id}} {% if reserva_confirmada %} checked {% endif %}">
    <label for="confirmacao{{forloop.counter}}">Confirmar? - {{reserva.data_evento}} - {{reserva.pessoas}}</label>
    <br/> {% endfor %}
    <input type="submit" value="Atualizar">
</form>
{% endblock conteudo %}

reservas/templates/reservas.html
{% extends "base.html" %} {% block conteudo %}
<h1>{{cliente.nome}}</h1>
<ul>
    {% for reserva in cliente.reservas_confirmadas %}
    <li>Data reserva: {{reserva.data_reserva}} -- Data evento: {{reserva.data_evento}} -- Qtde de pessoas: {{reserva.pessoas}}</li>
    {% endfor %}
</ul>
<a href="{% url 'reservas:detalhe' cliente.id %}">Confirmar mais reservas?</a>
{% endblock conteudo %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/style.css' %}" />
    <script src="main.js"></script>
</head>
<header>
    {% if user.is_authenticated %}
        <p>Hi, {{user.username}}</p>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <p>Vc n esta logado!</p>
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
</header>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/bloguinho/detail.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'home' %}">Ver todos</a>

<h1>Postinho</h1>

<div>{{post.author}}</div>
<div>{{post.body}}</div>

<a href="{% url 'post_edit' post.id %}">Editar</a>
<a href="{% url 'post_delete' post.id %}">Deletar</a>
    
{% endblock content %}

templates/bloguinho/home.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'post_create' %}">Novo postin</a>
<h1>Postinhos</h1>
{% for post in object_list %}
<div>{{post.body}}</div>
<a href="{% url 'post_detail' post.id %}">Ver</a>

{% endfor %}

{% endblock content %}

templates/bloguinho/new_post.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>

{% endblock content %}

templates/bloguinho/post_delete.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <h4>Tem certeza que quer deletar?</h4>
    <input type="submit" value="Confirmar">
</form>

{% endblock content %}

templates/bloguinho/post_edit.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>

{% endblock content %}

templates/reservas/detalhe.html
{% extends "base.html" %} {% block conteudo %}
<h1>{{cliente.nome}}</h1>
{% if error_message %}
<p>
    <strong>{{error_message}}</strong>
</p>
{% endif %}

<form action="{% url 'reservas:confirma' cliente.id %}" method="post">
    {% csrf_token %} {% for reserva in cliente.reservas_nao_confirmadas %}
    <input type="checkbox" name="confirmacao" id="confirmacao{{forloop.counter}}" value="{{reserva.id}} {% if reserva_confirmada %} checked {% endif %}">
    <label for="confirmacao{{forloop.counter}}">Confirmar? - {{reserva.data_evento}} - {{reserva.pessoas}}</label>
    <br/> {% endfor %}
    <input type="submit" value="Atualizar">
</form>

{% endblock conteudo %}

templates/reservas/index.html
 {% extends "base.html" %} {% block conteudo %} {% if object_list %}
<ul>
    {% for cliente in object_list %}
    <li>
        <a href="{% url 'reservas:reservas' cliente.id %}">{{cliente.nome}}</a>
    </li>
    {% endfor %}
</ul>
{% endif %} {% endblock conteudo %}

templates/reservas/reservas.html
{% extends "base.html" %} 
{% block conteudo %}

<h1>{{cliente.nome}}</h1>
<ul>
    {% for reserva in cliente.reservas_confirmadas %}
    <li>Data reserva: {{reserva.data_reserva}} -- Data evento: {{reserva.data_evento}} -- Qtde de pessoas: {{reserva.pessoas}}</li>
    {% endfor %}
</ul>
<a href="{% url 'reservas:detalhe' cliente.id %}">Confirmar mais reservas?</a>

{% endblock conteudo %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}

<h2>Sign Up</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
</form>

{% endblock content %}